s = input()
L = s.count('L')
M = s.count('M')
S = s.count('S')
print((L-s[:L].count('L'))+(M-s[L:L+M].count('M'))-min(s[L:L+M].count('L'),s[:L].count('M')))
print((L-s[:L].count('L')))
print((M-s[L:L+M].count('M')))
print(min(s[L:L+M].count('L'),s[:L].count('M')))
print(min(s[L:L+M].count('L')))